name: nsg_data
description: Data object model and data exchange with C# server
version: 1.0.0
homepage: https://github.com/zenalex/nsg_data
publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # nsg_controls:
  #   path: ../nsg_controls
  shared_preferences: ^2.5.3
  flutter_multi_formatter: ^2.13.10
  dio: ^5.4.3+1
  get: ^5.0.0-beta.52
  # get:
  #   path:
  #     ../getx
  retry: ^3.1.0
  event: ^2.0.5
  pedantic: ^1.11.1
  intl: ^0.20.2
  jiffy: ^6.0.0
  uuid: ^4.2.1
  timeago: ^3.5.0

  hive_ce: ^2.10.1
  path_provider: ^2.0.11
  package_info_plus: ^8.0.2
  device_info_plus: ^11.0.0
  excel:
    git: https://github.com/zenalex/excel.git
  #Выбор файлов на устройстве
  file_picker: ^8.1.4
  web: ^1.1.1

  # appmetrica_plugin: ^1.1.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo-wfrs.png
    - lib/assets/no_image.jpg
    - lib/assets/titan-back.png
