name: nsg_data
description: Data object model and data exchange with C# server
version: 0.2.0
homepage: https://github.com/zenalex/nsg_data
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  nsg_controls:
    path: 
      ../nsg_controls
  shared_preferences: ^2.0.6
  flutter_multi_formatter: ^2.10.2
  dio: ^4.0.6
  get: ^5.0.0-beta.52
  # get:
  #   path: 
  #     ../getx
  retry: ^3.1.0
  event: ^2.0.5
  pedantic: ^1.11.1
  intl: ^0.18.0
  jiffy: ^5.0.0 
  uuid: ^3.0.6

  hive: ^2.2.3
  path_provider: ^2.0.11
  # appmetrica_plugin: ^1.1.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  

  assets:
    - lib/assets/logo-wfrs.png
    - lib/assets/no_image.jpg
    - lib/assets/titan-back.png