name: nsg_data
description: Data object model and data exchange with C# server
version: 0.0.4
homepage: https://github.com/zenalex/nsg_data

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: '>=0.5.12 <2.0.0'
  flutter_multi_formatter: ^1.1.6
  dio: ^3.0.10
  get: ^3.17.1
  connectivity: ^0.4.9+5
  retry: ^3.0.1
  event: ^1.1.4
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.4
  

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo-wfrs.png